name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 1.0.3
homepage: https://github.com/anicdh
author: andoan <anic.dh@gmail.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  bip39: ^1.0.3
  bip32: ^1.0.5
  pointycastle: ^1.0.0-rc2
  hex: ^0.1.2
  bs58check: ^1.0.1
  meta: ^1.1.5
#  json_annotation: ^0.2.3

dev_dependencies:
  test: ^1.0.0
#  build_runner: ^0.8.0
#  json_serializable: ^0.5.0

