name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.3
homepage: https://github.com/anicdh
author: andoan <anic.dh@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bip39: ^1.0.6
  bip32: 
    git: 
      url: https://github.com/peercoin/bip32-dart.git
  pointycastle: ^3.0.1
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.4.0
  bech32: 
    git:
      url: https://github.com/saeveritt/bech32.git
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.17.5
